### ISSUE TITLE
Apollo:  Automatic scheduled security errata runs

### ISSUE THREAD

**Issue by skip77** [resf/distro-tools#1]
Security errata at errata.build.resf.org should be updated on an automatic schedule, without any human intervention.

I think 3 times a day (every 8 hours) is quite reasonable.  Strikes a balance between having timely security info, while not being in constant-update mode.

I have no idea how to implement this, but I assume it's a cron job somewhere?  ;-)

**Comment by NeilHanlon** [comment]
Resolved by #2
